[build]
publish = "build"

[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[build.processing]
html = { pretty_urls = true }
images = { compress = true }
[[redirects]]
from = "/*"
to = "/views/index.html"
status = 200
